### PR TITLE
remove swaps added to RL plugin

### PR DESCRIPTION
**Pull request by Blackberry0Pie**
Fremmy boots and Mythical cape are swapped with the "Teleport item" option. Con cape has "Tele to POH". All others use a SwapMode.

### CODE REVIEW

**Comment by raiyni** [comment]
Mythical cape and Fremmy boots were an anti swap thing, I think?

**Comment by Blackberry0Pie** [comment]
Currently they only work to add the teleport option if RL:MES Teleport item is unchecked.

**Comment by raiyni** [comment]
Let me clarify, they were meant to be used with runelite teleport off.

**Comment by Blackberry0Pie** [comment]
removed removal of mythical cape and fremmy boots

**Pull request merged**
