### PR TITLE
Added Sickle (b) menu swap for Cast Bloom

### PR DESCRIPTION
**Pull request by JakeWags**
As title says. Default option is Wield, can be swapped to Cast Bloom or Wield
Use case: gathering Mort Myre Fungus, makes this one click rather than 2. Since this is a repetitive action which is also done by almost every ironman (and many main accounts), this would be a valuable addition.
Screenshot (2)
Screenshot (4)

### CODE REVIEW

**Comment by raiyni** [comment]
This can probably be a boolean config using a contains check like hoop snake if it's only wield or bloom?

**Comment by JakeWags** [comment]
> 
> 
> This can probably be a boolean config using a contains check like hoop snake if it's only wield or bloom?

I did it this way because the Fremennik Sea Boots have only two options and use the dropdown. I think the dropdown is more intuitive as a user, but I can change it to a boolean contains check.

**Comment by raiyni** [comment]
Cast bloom can also be used on the other sickle types too, right?

**Comment by JakeWags** [comment]
Are there other sickle types?

**Comment by raiyni** [comment]
The gem sickles

**Comment by JakeWags** [comment]
I haven't completed A Taste of Hope on my ironman (my only acc) so I can't test the compatibility with the gem sickles or the flails, but it works fine with the silver sickle (b) so I don't see why it wouldn't work with those.

**Comment by raiyni** [comment]
0af0b7e actually covered that scenario and I didn't read it beforehand.

For future reference, when you contribute to any repo (not just mine) don't submit the PR from the master branch.

**Pull request merged**
