### PR TITLE
Reqs - 77,73,68,67,62,43,50,33

### PR DESCRIPTION
**Pull request by snarLox**
Standard Swaps: 73,68,67,62,43,50,33
Mode Swap: Mythical Cape(77)

### CODE REVIEW

**Comment by raiyni** [comment]
Can you use the runelite formatter please?

**Comment by snarLox** [comment]
How?

**Comment by raiyni** [comment]
https://github.com/runelite/runelite/wiki/Code-Conventions

**Comment by snarLox** [comment]
Done @raiyni

**Comment by raiyni** [comment]
Reopening this under a new branch I have access to.

**Pull request closed without merging**
